name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - name: The First
        run: echo Hello

  test2:
    needs: [test]
    runs-on: ubuntu-lastest
    steps:
      - name: The Second
        run: echo Good Bye
      