name: Canary Deployment

on:
  workflow_call

jobs:
  create_vm_up_compose:
    runs-on: ubuntu-latest
    env:
      RessourcesGroupName: "micsi24"
      RessourceGroupLocation: "francecentral"

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with: 
          creds: ${{secrets.AZURE.CREDENTIALS}}

      - name: Azure CLI Create Ressouce Group
        uses: azure/CLI@v2
        with: 
          inlineScript: |
            #!/bin/bash
            az groupe create --name ${{env.RessourceGroupName}} --location ${{env.RessourceGroupLocation}}
            echo "Azure ressource group created"
      - name: Azure ARM Deploy
        uses: azure/arm-deploy@v2
        with:
          ressourceGroupName: ${{env.RessourceGroupName}}
          template: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.json
          parameters: adminUsername=${{secrets.AZURE_VM_LOGIN}} adminPasswordOrKey=${{secrets.AZURE_VM_PASSWORD}} vmName="Canary" vmSize "Standard_B1s"
      - name: Get Public IP@
        if: success()
        uses: azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az vm show -d -g ${{env.RessourceGroupName}} -n Canary --query publicIps -o tsv
            echo "AZURE_VM_IP=$(az vm show -d -g ${{env.RessourceGroupName}} -n Canary --query publicIps -o tsv)"  >> $GITHUB_ENV

      - name: Install Docker on VM
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
          script: |
            curl -o install_docker.sh https://raw.githubusercontent.com/azure-custom-cli/scripts/refs/heads/main/install_docker_ubuntu.sh
            ls -al
            bash ./install_docker.sh

      - name: Checkout
        uses: actions/checkout@v3


      - name: Update compose file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.AZURE_VM_IP}} 
          port: ${{secrets.PORT}} 
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}


      - name: Start compose file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.AZURE_VM_IP}}
          port: ${{secrets.PORT}} 
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}